FROM public.ecr.aws/bitnami/spark:3.5

WORKDIR /app

USER root
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY scripts/spark_transform.py ./scripts/
COPY .env .

# Spark-submit command with the Kafka package
CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1", "scripts/spark_transform.py"]